In [3]:
import numpy as np
import pandas as pd
import matplotlib as pyplot

from scipy import ndimage  # спецификатор для работы с изображениями
from scipy import misc 
from PIL import Image
import scipy.stats as sps
%matplotlib inline

In [18]:
a=np.random.sample((10,10))
b=np.random.sample((10,10))

In [15]:
a.ndim
a.shape
print(a)
print(b)

(10, 10)

In [80]:

def mult(a,b):
    z=[[0 for col in range(a.shape[0])] for row in range(b.shape[1])]
    for i in range(a.shape[0]): 
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                 z[i][j]+=a[i][k]*b[k][j]
    
    print(z)
    pass


In [81]:
def np_mult(a, b):
    z=np.dot(a,b)
    print(z)   
    pass

In [2]:
def stupid_sec_av(A):
    S = [0 for i in range(len(A))]
    for i in range(len(A)):
        S[i]=sum(S)+A[i]
    for i in range(len(A)):
        S[i]=S[i]/i
    return S

In [4]:
A = sps.uniform.rvs(size=10 ** 7)

In [5]:
A

array([0.62374346, 0.70613264, 0.9334422 , ..., 0.88836587, 0.3876322 ,
       0.26253822])

In [6]:
stupid_sec_av(A)

KeyboardInterrupt: 

In [7]:
[range(10)]

[range(0, 10)]

In [14]:
for i in range(5):
...     print(i)

0
1
2
3
4


In [15]:
range(5)

range(0, 5)

In [16]:
type(range(5))

range

In [17]:
arange(5)

NameError: name 'arange' is not defined

In [150]:
a=list(range(10))
s=[0]*10

In [27]:
for i in range(10):
    s[i]+=s[i]
    

In [141]:
s[5]=sum(a[:5+1])

In [151]:
for i in range(10):
    s[i]=sum(a[:i+1])/(i+1)
    

In [152]:
s

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [53]:
sum(s[:i])

45

In [99]:
sum(a[:5])

TypeError: 'int' object is not callable

In [102]:
a[:5]

[0, 1, 2, 3, 4]

In [103]:
sum(a[:5])

TypeError: 'int' object is not callable

In [105]:
sum([0, 1, 2, 3, 4])

TypeError: 'int' object is not callable

In [106]:
sum

45

In [107]:
sum

45

In [108]:
del(sum)

In [109]:
del sum

NameError: name 'sum' is not defined

In [110]:
sum

<function sum(iterable, start=0, /)>

In [153]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [154]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [1]:
import numpy as np

c = np.array([ True, False, False], bool)

print(np.any(c))

True


In [2]:
a = np.array([1, 5, 0], float)

print (np.where(a != 0, 1 / a, a))

[1.  0.2 0. ]


C:\Users\serge\.conda\envs\py36\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
a=[[5,1,-2,0],[0,3,4,3],[2,3,1,1]]
b=[[1,-3],[2,-2],[3,-1],[0,0]]

In [6]:
sum(np.dot(a,b))

array([ 30, -38])

In [ ]:
sum[]